/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import modelo.Persona;
import modelo.Usuario;
import servicios.ServicioConfiguracion;
import servicios.ServicioUsuario;
import sesion.Sesion;
import utils.UtileriaVista;
import utils.constantes.CharArrayUtils;
import utils.constantes.Constantes;
import utils.constantes.RespuestaGeneral;

/**
 *
 * @author student
 */
public class pCrearUsuario extends javax.swing.JPanel {

    /**
     * Creates new form pCrearUsuario
     */
    ServicioConfiguracion _configuracion;
    Sesion sesion;
    private boolean esRestaurar;

    public pCrearUsuario(Sesion sesion, boolean esRestaurar) {
        initComponents();
        this.sesion = sesion;
        this.esRestaurar = esRestaurar;
        this._configuracion = new ServicioConfiguracion();
        this.iniciarVista();
    }

    public void iniciarVista() {
        ComboBoxModel<String> modeloPreguntasRecuperacion1 = new DefaultComboBoxModel<String>(Constantes.PREGUNTAS_SEGURIDAD);
        ComboBoxModel<String> modeloPreguntasRecuperacion2 = new DefaultComboBoxModel<String>(Constantes.PREGUNTAS_SEGURIDAD);
        ComboBoxModel<String> modeloPreguntasRecuperacion3 = new DefaultComboBoxModel<String>(Constantes.PREGUNTAS_SEGURIDAD);
        this.comboPreguntaRecuperacion1.setModel(modeloPreguntasRecuperacion1);
        this.comboPreguntaRecuperacion2.setModel(modeloPreguntasRecuperacion2);
        this.comboPreguntaRecuperacion3.setModel(modeloPreguntasRecuperacion3);
        if (esRestaurar) {
            btnCrearConfiguracion.setText("Crear configuración");
        } else {
            btnCrearConfiguracion.setText("Crear alumno");
        }
    }

    public pCrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombres = new RSMaterialComponent.RSTextFieldMaterial();
        txtApellidos = new RSMaterialComponent.RSTextFieldMaterial();
        txtCarnet = new RSMaterialComponent.RSTextFieldMaterial();
        txtClave = new RSMaterialComponent.RSPasswordMaterial();
        txtRepetirClave = new RSMaterialComponent.RSPasswordMaterial();
        txtCorreo = new RSMaterialComponent.RSTextFieldMaterial();
        comboPreguntaRecuperacion1 = new RSMaterialComponent.RSComboBoxMaterial();
        txtRespuesta1 = new RSMaterialComponent.RSTextFieldMaterial();
        comboPreguntaRecuperacion2 = new RSMaterialComponent.RSComboBoxMaterial();
        txtRespuesta2 = new RSMaterialComponent.RSTextFieldMaterial();
        comboPreguntaRecuperacion3 = new RSMaterialComponent.RSComboBoxMaterial();
        txtRespuesta3 = new RSMaterialComponent.RSTextFieldMaterial();
        btnCrearConfiguracion = new RSMaterialComponent.RSButtonShapeIcon();
        btnCancelar = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel1 = new javax.swing.JLabel();

        txtNombres.setPlaceholder("Nombres");
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });

        txtApellidos.setPlaceholder("Apellidos");
        txtApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidosActionPerformed(evt);
            }
        });

        txtCarnet.setPlaceholder("Carnét");
        txtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnetActionPerformed(evt);
            }
        });

        txtClave.setPlaceholder("Clave de acceso");

        txtRepetirClave.setPlaceholder("Repetir clave de acceso");

        txtCorreo.setPlaceholder("Correo");
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });

        comboPreguntaRecuperacion1.setColorMaterial(new java.awt.Color(102, 102, 102));

        txtRespuesta1.setForeground(new java.awt.Color(0, 0, 0));
        txtRespuesta1.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtRespuesta1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRespuesta1.setPhColor(new java.awt.Color(0, 0, 0));
        txtRespuesta1.setPlaceholder("Digite la respuesta..");
        txtRespuesta1.setSelectionColor(new java.awt.Color(0, 0, 0));

        comboPreguntaRecuperacion2.setColorMaterial(new java.awt.Color(102, 102, 102));

        txtRespuesta2.setForeground(new java.awt.Color(0, 0, 0));
        txtRespuesta2.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtRespuesta2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRespuesta2.setPhColor(new java.awt.Color(0, 0, 0));
        txtRespuesta2.setPlaceholder("Digite la respuesta..");
        txtRespuesta2.setSelectionColor(new java.awt.Color(0, 0, 0));

        comboPreguntaRecuperacion3.setColorMaterial(new java.awt.Color(102, 102, 102));

        txtRespuesta3.setForeground(new java.awt.Color(0, 0, 0));
        txtRespuesta3.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtRespuesta3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtRespuesta3.setPhColor(new java.awt.Color(0, 0, 0));
        txtRespuesta3.setPlaceholder("Digite la respuesta..");
        txtRespuesta3.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnCrearConfiguracion.setBackground(new java.awt.Color(33, 58, 86));
        btnCrearConfiguracion.setText("Crear configuración");
        btnCrearConfiguracion.setToolTipText("");
        btnCrearConfiguracion.setBackgroundHover(new java.awt.Color(33, 68, 86));
        btnCrearConfiguracion.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCrearConfiguracion.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCrearConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCrearConfiguracion.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CACHED);
        btnCrearConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearConfiguracionActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(251, 205, 6));
        btnCancelar.setText("CANCELAR");
        btnCancelar.setBackgroundHover(new java.awt.Color(251, 174, 6));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCancelar.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnCancelar.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelar.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnCancelar.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCancelar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/img/recuperacion.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel1))
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboPreguntaRecuperacion2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboPreguntaRecuperacion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtRespuesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRepetirClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCrearConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtRespuesta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboPreguntaRecuperacion3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtRespuesta3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboPreguntaRecuperacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRespuesta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboPreguntaRecuperacion2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRepetirClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtRespuesta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboPreguntaRecuperacion3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtRespuesta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCrearConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidosActionPerformed

    private void txtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnetActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    public Usuario capturarDatos() {
        char[] claveSinCifrar = txtClave.getPassword();
        char[] repetirClaveSinCifrar = txtRepetirClave.getPassword();

        Persona persona = new Persona();
        persona.setNombres(txtNombres.getText().trim());
        persona.setApellidos(txtApellidos.getText().trim());
        persona.setTipo(Constantes.TIPO_ALUMNO);
        persona.setCarnet(txtCarnet.getText().trim());

        Usuario usuario = new Usuario();
        usuario.setNombre(txtCarnet.getText().trim());
        usuario.setCorreo(txtCorreo.getText().trim());

        //la clave se cifra en el servicio
        //usuario.setClave(null);
        if (!Arrays.equals(claveSinCifrar, repetirClaveSinCifrar)) {
            JOptionPane.showMessageDialog(this, "Las claves no coinciden", "Mensaje", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        usuario.setResetear_clave(Constantes.NO_RESETEAR_CLAVE);

        usuario.setPregunta1(comboPreguntaRecuperacion1.getSelectedIndex());
        usuario.setRespuesta1(txtRespuesta1.getText().trim());
        usuario.setPregunta2(comboPreguntaRecuperacion2.getSelectedIndex());
        usuario.setRespuesta2(txtRespuesta2.getText().trim());
        usuario.setPregunta3(comboPreguntaRecuperacion3.getSelectedIndex());
        usuario.setRespuesta3(txtRespuesta3.getText().trim());

        usuario.setPersona(persona);
        return usuario;
    }
    private void btnCrearConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearConfiguracionActionPerformed

//        if (esRestaurar) {
//            //new utils.alertas.AlertError(this, true, "OCURRIO UN PROBLEM").setVisible(true);
//            int salida = JOptionPane.showConfirmDialog(this, "Está a punto de crear un nuevo archivo basado en la versión inicial del sistema. \nEl nuevo archivo no contendrá ningun dato que usted haya ingresado incluyendo catálogos, partidas, etc.\nEl nuevo archivo contendrá docentes creados por defecto en la versión inicial\nEstará con el catálogo inicial, sin ninguna partida \n¿Esta seguro de continuar?",
//                    "¡Restaurar a versión inicial!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//            //System.out.println(salida);
//            if (salida == 0) {
//                RespuestaGeneral resp = this._configuracion.crear(usuario, claveSinCifrar);
//                if (resp.esExitosa()) {
//                    JOptionPane.showMessageDialog(this, resp.getMensaje(), "INFORMACIÓN", UtileriaVista.devolverCodigoMensaje(resp));
//                    vInicio vistaInicio = new vInicio();
//                    vistaInicio.setVisible(true);
//                } else {
//                    JOptionPane.showMessageDialog(this, resp.getMensaje(), "Mensaje", UtileriaVista.devolverCodigoMensaje(resp));
//                }
//            }
//        } else {
//            int salida = JOptionPane.showConfirmDialog(this, "Está a punto de crear un nuevo alumno\nEl alumno pasará a ser propietario de este archivo y no se podrá cambiar\n¿Esta seguro de continuar?",
//                    "¡Crear alumno!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
//            if (salida == 0) {
//                ServicioUsuario _usuario = new ServicioUsuario(sesion.rutaConexion);
//
//                RespuestaGeneral resp = _usuario.crearAlumno(usuario, claveSinCifrar);
//                if (resp.esExitosa()) {
//                    JOptionPane.showMessageDialog(this, resp.getMensaje(), "INFORMACIÓN", UtileriaVista.devolverCodigoMensaje(resp));
//                    vInicio vistaInicio = new vInicio();
//                    vistaInicio.setVisible(true);
//
//                } else {
//                    JOptionPane.showMessageDialog(this, resp.getMensaje(), "Mensaje", UtileriaVista.devolverCodigoMensaje(resp));
//                }
//            }
//        }
//
//        //limpiar el array de char, en caso de volcado de memoria, no esté la clave
//        CharArrayUtils.limpiar(claveSinCifrar);
//        CharArrayUtils.limpiar(repetirClaveSinCifrar);
    }//GEN-LAST:event_btnCrearConfiguracionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        vInicio inicio = new vInicio();
        inicio.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnCancelar;
    private RSMaterialComponent.RSButtonShapeIcon btnCrearConfiguracion;
    private RSMaterialComponent.RSComboBoxMaterial comboPreguntaRecuperacion1;
    private RSMaterialComponent.RSComboBoxMaterial comboPreguntaRecuperacion2;
    private RSMaterialComponent.RSComboBoxMaterial comboPreguntaRecuperacion3;
    private javax.swing.JLabel jLabel1;
    private RSMaterialComponent.RSTextFieldMaterial txtApellidos;
    private RSMaterialComponent.RSTextFieldMaterial txtCarnet;
    private RSMaterialComponent.RSPasswordMaterial txtClave;
    private RSMaterialComponent.RSTextFieldMaterial txtCorreo;
    private RSMaterialComponent.RSTextFieldMaterial txtNombres;
    private RSMaterialComponent.RSPasswordMaterial txtRepetirClave;
    private RSMaterialComponent.RSTextFieldMaterial txtRespuesta1;
    private RSMaterialComponent.RSTextFieldMaterial txtRespuesta2;
    private RSMaterialComponent.RSTextFieldMaterial txtRespuesta3;
    // End of variables declaration//GEN-END:variables
}
