/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import modelo.Cuenta;
import servicios.ServicioCuenta;
import servicios.ServicioCuentaBalance;
import servicios.ServicioFormula;
import servicios.ServicioFormulaParametro;
import sesion.Sesion;

/**
 *
 * @author student
 */
public class vBalanceGeneral extends javax.swing.JPanel {

    /**
     * Creates new form vBalanceGeneral
     */
    
    Sesion sesion;
    ServicioCuenta _cuenta;
    ServicioCuentaBalance _cuentaBalance;
    
    public vBalanceGeneral() {
        initComponents();
        this.sesion = sesion;
        this._cuenta = new ServicioCuenta(sesion.rutaConexion);
        this._cuentaBalance = new ServicioCuentaBalance(sesion.rutaConexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerBalanceGeneral = new RSMaterialComponent.RSButtonShapeIcon();

        btnVerBalanceGeneral.setBackground(new java.awt.Color(251, 205, 6));
        btnVerBalanceGeneral.setText("Ver balance general");
        btnVerBalanceGeneral.setBackgroundHover(new java.awt.Color(251, 174, 6));
        btnVerBalanceGeneral.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnVerBalanceGeneral.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnVerBalanceGeneral.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnVerBalanceGeneral.setForegroundText(new java.awt.Color(0, 0, 0));
        btnVerBalanceGeneral.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.BOOK);
        btnVerBalanceGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerBalanceGeneralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerBalanceGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVerBalanceGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(244, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerBalanceGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBalanceGeneralActionPerformed
        verBalanceGeneral();
    }//GEN-LAST:event_btnVerBalanceGeneralActionPerformed

    private void verBalanceGeneral() {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnVerBalanceGeneral;
    // End of variables declaration//GEN-END:variables
}
