/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import dao.daoCicloContable;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CicloContable;
import modelo.dtoCicloContable;
import servicios.ServicioCicloContable;
import utils.constantes.RespuestaGeneral;

/**
 *
 * @author vacev
 */
public class vCicloContable extends javax.swing.JPanel {

    /**
     * Creates new form vCicloContable
     */
    ServicioCicloContable _cicloContable = new ServicioCicloContable();
    ArrayList<dtoCicloContable> listaCiclosContables = new ArrayList<>();
    CicloContable cicloContableModel = new CicloContable();
    
    DefaultTableModel dtm = new DefaultTableModel();
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    public vCicloContable() {
        initComponents();
        this.setModel();
        this.obtenerListadoCiclosContables();
    }
    
    public void setModel() {
        String[] cabecera = {"Titulo","Desde","Hasta","Catalogo"};
        dtm.setColumnIdentifiers(cabecera);
        tblCicloContable.setModel(dtm);
    }
    
    public void setDatos() {
        Object[] datos = new Object[dtm.getColumnCount()];
        for (dtoCicloContable ciclo : listaCiclosContables) {
            datos[0] = ciclo.getTitulo();
            datos[1] = sdf.format(ciclo.getDesde());
            datos[2] = sdf.format(ciclo.getHasta());
            datos[3] = ciclo.getCatalogo();
            dtm.addRow(datos);
        }
        tblCicloContable.setModel(dtm);
    }
    
    public void obtenerListadoCiclosContables() {
        this.listaCiclosContables = new ArrayList<>();
        tblCicloContable.clearSelection();
        this.limiparTabla();
        RespuestaGeneral rs = _cicloContable.obtenerLista();
        if (rs.esExitosa()) {
            this.listaCiclosContables = (ArrayList<dtoCicloContable>)rs.getDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el listado", "ALERTA", JOptionPane.ERROR_MESSAGE);
        }
        this.setDatos();
    }

    public void limiparTabla() {
        for (int i = 0; i < tblCicloContable.getRowCount(); i++) {
            dtm.removeRow(i);
            i-=1;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTitulo = new RSMaterialComponent.RSTextFieldMaterial();
        rSButtonShapeIcon10 = new RSMaterialComponent.RSButtonShapeIcon();
        btnGuardar = new RSMaterialComponent.RSButtonShapeIcon();
        listCatalogo = new RSMaterialComponent.RSComboBoxMaterial();
        txtHasta = new newscomponents.RSDateChooser();
        txtDesde = new newscomponents.RSDateChooser();
        rSButtonShapeIcon11 = new RSMaterialComponent.RSButtonShapeIcon();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCicloContable = new rojerusan.RSTableMetro();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos de ciclo contable  "));

        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTitulo.setPhColor(new java.awt.Color(0, 0, 0));
        txtTitulo.setPlaceholder("Digite el titulo del ciclo contable");
        txtTitulo.setSelectionColor(new java.awt.Color(0, 0, 0));

        rSButtonShapeIcon10.setBackground(new java.awt.Color(251, 205, 6));
        rSButtonShapeIcon10.setText("CANCELAR");
        rSButtonShapeIcon10.setBackgroundHover(new java.awt.Color(251, 174, 6));
        rSButtonShapeIcon10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonShapeIcon10.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon10.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon10.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon10.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon10.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        rSButtonShapeIcon10.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        rSButtonShapeIcon10.setSizeIcon(20.0F);
        rSButtonShapeIcon10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon10ActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(33, 58, 86));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setBackgroundHover(new java.awt.Color(33, 68, 86));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnGuardar.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CACHED);
        btnGuardar.setSizeIcon(20.0F);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        listCatalogo.setBorder(null);
        listCatalogo.setColorMaterial(new java.awt.Color(102, 102, 102));

        txtHasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHasta.setFormatDate("dd-MM-yyyy");

        txtDesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDesde.setFormatDate("dd-MM-yyyy");
        txtDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDesdePropertyChange(evt);
            }
        });

        rSButtonShapeIcon11.setBackground(new java.awt.Color(0, 153, 0));
        rSButtonShapeIcon11.setText("SELECCIONAR");
        rSButtonShapeIcon11.setBackgroundHover(new java.awt.Color(0, 255, 51));
        rSButtonShapeIcon11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonShapeIcon11.setForegroundHover(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon11.setForegroundIcon(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon11.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon11.setForegroundText(new java.awt.Color(0, 0, 0));
        rSButtonShapeIcon11.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        rSButtonShapeIcon11.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        rSButtonShapeIcon11.setSizeIcon(20.0F);
        rSButtonShapeIcon11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonShapeIcon11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 146, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rSButtonShapeIcon11, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rSButtonShapeIcon10, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(listCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSButtonShapeIcon10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rSButtonShapeIcon11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Detalles de ciclo contable  "));

        tblCicloContable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCicloContable.setBackgoundHead(new java.awt.Color(153, 153, 153));
        tblCicloContable.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tblCicloContable.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblCicloContable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCicloContable.setShowGrid(true);
        tblCicloContable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCicloContableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCicloContable);
        tblCicloContable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonShapeIcon10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon10ActionPerformed
       this.limpiarForm();
    }//GEN-LAST:event_rSButtonShapeIcon10ActionPerformed

    public void limpiarForm() {
        cicloContableModel = new CicloContable();
        txtDesde.setDate(new Date());
        txtHasta.setDate(new Date());
        txtTitulo.setText("");
        tblCicloContable.clearSelection();
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // setear info al modelo
        this.cicloContableModel.setTitulo(this.txtTitulo.getText());
        this.cicloContableModel.setDesde(this.txtDesde.getDate());
        this.cicloContableModel.setHasta(this.txtHasta.getDate());
        this.cicloContableModel.setId_catalogo(1);
        // guardamos la info
        // verificamos si es NUEVO
        btnGuardar.setEnabled(false);
        if (this.cicloContableModel.getId() < 0) {
            RespuestaGeneral rs = _cicloContable.insertar(this.cicloContableModel);
            if (rs.esExitosa()) {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                this.obtenerListadoCiclosContables();
            } else {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "¡ALERTA!", JOptionPane.ERROR_MESSAGE);
            }
        
            // verificamos si es NUEVO
        } else {
            RespuestaGeneral rs = _cicloContable.editar(this.cicloContableModel);
            if (rs.esExitosa()) {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                this.obtenerListadoCiclosContables();
            } else {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "¡ALERTA!", JOptionPane.ERROR_MESSAGE);
            }
        }
        btnGuardar.setEnabled(true);
        this.limpiarForm();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rSButtonShapeIcon11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonShapeIcon11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSButtonShapeIcon11ActionPerformed

    private void tblCicloContableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCicloContableMouseClicked
        int row = tblCicloContable.getSelectedRow();
        // seteamos el ID para editar
        cicloContableModel.setId(this.listaCiclosContables.get(row).getId());
        txtTitulo.setText(this.listaCiclosContables.get(row).getTitulo());
        txtDesde.setDate(this.listaCiclosContables.get(row).getDesde());
        txtDesde.setFormatDate("dd-MM-yyyy");
        txtHasta.setDate(this.listaCiclosContables.get(row).getHasta());
        txtHasta.setFormatDate("dd-MM-yyyy");
    }//GEN-LAST:event_tblCicloContableMouseClicked

    private void txtDesdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDesdePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesdePropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSComboBoxMaterial listCatalogo;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon10;
    private RSMaterialComponent.RSButtonShapeIcon rSButtonShapeIcon11;
    private rojerusan.RSTableMetro tblCicloContable;
    private newscomponents.RSDateChooser txtDesde;
    private newscomponents.RSDateChooser txtHasta;
    private RSMaterialComponent.RSTextFieldMaterial txtTitulo;
    // End of variables declaration//GEN-END:variables
}
