/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.CicloContable;
import modelo.dtoCicloContable;
import servicios.ServicioCicloContable;
import utils.constantes.RespuestaGeneral;

/**
 *
 * @author vacev
 */
public class vConfigContabilidad extends javax.swing.JPanel {

    /**
     * Creates new form vConfigContabilidad
     */
    
    ServicioCicloContable _cicloContable = new ServicioCicloContable();
    ArrayList<dtoCicloContable> listaCiclosContables = new ArrayList<>();
    CicloContable cicloContableModel = new CicloContable();
    
    DefaultTableModel dtm = new DefaultTableModel();
    
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    public vConfigContabilidad() {
        initComponents();
        this.cargarInfoSegunTab();
    }

    
    public void setModelCicloContable() {
        String[] cabecera = {"Titulo","Desde","Hasta","Catalogo"};
        dtm.setColumnIdentifiers(cabecera);
        tblCicloContable.setModel(dtm);
    }
    
    public void setDatosCicloContable() {
        Object[] datos = new Object[dtm.getColumnCount()];
        for (dtoCicloContable ciclo : listaCiclosContables) {
            datos[0] = ciclo.getTitulo();
            datos[1] = sdf.format(ciclo.getDesde());
            datos[2] = sdf.format(ciclo.getHasta());
            datos[3] = ciclo.getCatalogo();
            dtm.addRow(datos);
        }
        tblCicloContable.setModel(dtm);
    }
    
    public void obtenerListadoCiclosContables() {
        this.listaCiclosContables = new ArrayList<>();
        tblCicloContable.clearSelection();
        this.limiparTablaCicloContable();
        RespuestaGeneral rs = _cicloContable.obtenerLista();
        if (rs.esExitosa()) {
            this.listaCiclosContables = (ArrayList<dtoCicloContable>)rs.getDatos();
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo obtener el listado", "ALERTA", JOptionPane.ERROR_MESSAGE);
        }
        this.setDatosCicloContable();
    }

    public void limiparTablaCicloContable() {
        for (int i = 0; i < tblCicloContable.getRowCount(); i++) {
            dtm.removeRow(i);
            i-=1;
        }
    }
    
    public void limpiarFormCicloContable() {
        cicloContableModel = new CicloContable();
        txtDesde.setDate(new Date());
        txtHasta.setDate(new Date());
        txtDesde.setFormatDate("dd-MM-yyyy");
        txtHasta.setFormatDate("dd-MM-yyyy");
        txtTitulo.setText("");
        btnEliminarCicloContable.setEnabled(false);
        tblCicloContable.clearSelection();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPanelContabilidad = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtTitulo = new RSMaterialComponent.RSTextFieldMaterial();
        btnCancelarCicloContable = new RSMaterialComponent.RSButtonShapeIcon();
        btnGuardarCicloContable = new RSMaterialComponent.RSButtonShapeIcon();
        listCatalogo = new RSMaterialComponent.RSComboBoxMaterial();
        txtHasta = new newscomponents.RSDateChooser();
        txtDesde = new newscomponents.RSDateChooser();
        btnEstablecerCicloContable = new RSMaterialComponent.RSButtonShapeIcon();
        btnEliminarCicloContable = new RSMaterialComponent.RSButtonShapeIcon();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCicloContable = new rojerusan.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();

        tabPanelContabilidad.setBackground(new java.awt.Color(255, 255, 255));
        tabPanelContabilidad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tabPanelContabilidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabPanelContabilidadStateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Registro y edición de ciclo contable  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        txtTitulo.setForeground(new java.awt.Color(0, 0, 0));
        txtTitulo.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtTitulo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtTitulo.setPhColor(new java.awt.Color(0, 0, 0));
        txtTitulo.setPlaceholder("Digite el titulo del ciclo contable");
        txtTitulo.setSelectionColor(new java.awt.Color(0, 0, 0));

        btnCancelarCicloContable.setBackground(new java.awt.Color(251, 205, 6));
        btnCancelarCicloContable.setText("CANCELAR");
        btnCancelarCicloContable.setBackgroundHover(new java.awt.Color(251, 174, 6));
        btnCancelarCicloContable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelarCicloContable.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnCancelarCicloContable.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelarCicloContable.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnCancelarCicloContable.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelarCicloContable.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCancelarCicloContable.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarCicloContable.setSizeIcon(18.0F);
        btnCancelarCicloContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCicloContableActionPerformed(evt);
            }
        });

        btnGuardarCicloContable.setBackground(new java.awt.Color(33, 58, 86));
        btnGuardarCicloContable.setText("GUARDAR");
        btnGuardarCicloContable.setBackgroundHover(new java.awt.Color(33, 68, 86));
        btnGuardarCicloContable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardarCicloContable.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnGuardarCicloContable.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarCicloContable.setSizeIcon(18.0F);
        btnGuardarCicloContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCicloContableActionPerformed(evt);
            }
        });

        listCatalogo.setBorder(null);
        listCatalogo.setColorMaterial(new java.awt.Color(102, 102, 102));

        txtHasta.setBackground(new java.awt.Color(153, 153, 153));
        txtHasta.setBgColor(new java.awt.Color(153, 153, 153));
        txtHasta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtHasta.setFormatDate("dd-MM-yyyy");

        txtDesde.setBackground(new java.awt.Color(153, 153, 153));
        txtDesde.setBgColor(new java.awt.Color(153, 153, 153));
        txtDesde.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDesde.setFormatDate("dd-MM-yyyy");
        txtDesde.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDesdePropertyChange(evt);
            }
        });

        btnEstablecerCicloContable.setBackground(new java.awt.Color(0, 153, 0));
        btnEstablecerCicloContable.setText("ESTABLECER CICLO POR DEFECTO");
        btnEstablecerCicloContable.setBackgroundHover(new java.awt.Color(0, 167, 0));
        btnEstablecerCicloContable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEstablecerCicloContable.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnEstablecerCicloContable.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEstablecerCicloContable.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnEstablecerCicloContable.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEstablecerCicloContable.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnEstablecerCicloContable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEstablecerCicloContable.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CHECK);
        btnEstablecerCicloContable.setSizeIcon(18.0F);
        btnEstablecerCicloContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstablecerCicloContableActionPerformed(evt);
            }
        });

        btnEliminarCicloContable.setBackground(new java.awt.Color(197, 0, 0));
        btnEliminarCicloContable.setText("ELIMINAR");
        btnEliminarCicloContable.setBackgroundHover(new java.awt.Color(242, 0, 0));
        btnEliminarCicloContable.setEnabled(false);
        btnEliminarCicloContable.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEliminarCicloContable.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnEliminarCicloContable.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnEliminarCicloContable.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnEliminarCicloContable.setForegroundText(new java.awt.Color(0, 0, 0));
        btnEliminarCicloContable.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnEliminarCicloContable.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.ERROR);
        btnEliminarCicloContable.setSizeIcon(18.0F);
        btnEliminarCicloContable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCicloContableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHasta, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                    .addComponent(listCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnGuardarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEstablecerCicloContable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(123, 123, 123))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnEstablecerCicloContable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(listCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Listado de ciclos contables  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        tblCicloContable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCicloContable.setBackgoundHead(new java.awt.Color(153, 153, 153));
        tblCicloContable.setBackgoundHover(new java.awt.Color(204, 204, 204));
        tblCicloContable.setColorPrimaryText(new java.awt.Color(0, 0, 0));
        tblCicloContable.setColorSecundaryText(new java.awt.Color(51, 51, 51));
        tblCicloContable.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tblCicloContable.setFontHead(new java.awt.Font("Arial", 1, 12)); // NOI18N
        tblCicloContable.setFontRowHover(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tblCicloContable.setFontRowSelect(new java.awt.Font("Arial", 1, 11)); // NOI18N
        tblCicloContable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        tblCicloContable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblCicloContable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCicloContable.setShowGrid(true);
        tblCicloContable.setShowVerticalLines(false);
        tblCicloContable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCicloContableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCicloContable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanelContabilidad.addTab("Ciclo Contable", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1311, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        tabPanelContabilidad.addTab("Catalogos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelContabilidad)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelContabilidad)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarCicloContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCicloContableActionPerformed
        this.limpiarFormCicloContable();
    }//GEN-LAST:event_btnCancelarCicloContableActionPerformed

    private void btnGuardarCicloContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCicloContableActionPerformed
        // setear info al modelo
        this.cicloContableModel.setTitulo(this.txtTitulo.getText());
        this.cicloContableModel.setDesde(this.txtDesde.getDate());
        this.cicloContableModel.setHasta(this.txtHasta.getDate());
        this.cicloContableModel.setId_catalogo(1);
        // guardamos la info
        // verificamos si es NUEVO
        btnGuardarCicloContable.setEnabled(false);
        if (this.cicloContableModel.getId() < 0) {
            RespuestaGeneral rs = _cicloContable.insertar(this.cicloContableModel);
            if (rs.esExitosa()) {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                this.obtenerListadoCiclosContables();
            } else {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "¡ALERTA!", JOptionPane.ERROR_MESSAGE);
            }

            // verificamos si es NUEVO
        } else {
            RespuestaGeneral rs = _cicloContable.editar(this.cicloContableModel);
            if (rs.esExitosa()) {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                this.obtenerListadoCiclosContables();
            } else {
                JOptionPane.showMessageDialog(null, rs.getMensaje(), "¡ALERTA!", JOptionPane.ERROR_MESSAGE);
            }
        }
        btnGuardarCicloContable.setEnabled(true);
        this.limpiarFormCicloContable();
    }//GEN-LAST:event_btnGuardarCicloContableActionPerformed

    private void txtDesdePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDesdePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDesdePropertyChange

    private void btnEstablecerCicloContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstablecerCicloContableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstablecerCicloContableActionPerformed

    private void tblCicloContableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCicloContableMouseClicked
        int row = tblCicloContable.getSelectedRow();
        // seteamos el ID para editar
        cicloContableModel.setId(this.listaCiclosContables.get(row).getId());
        txtTitulo.setText(this.listaCiclosContables.get(row).getTitulo());
        txtDesde.setDate(this.listaCiclosContables.get(row).getDesde());
        txtHasta.setDate(this.listaCiclosContables.get(row).getHasta());
        txtDesde.setFormatDate("dd-MM-yyyy");
        txtHasta.setFormatDate("dd-MM-yyyy");
        btnEliminarCicloContable.setEnabled(true);
    }//GEN-LAST:event_tblCicloContableMouseClicked

    private void tabPanelContabilidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelContabilidadStateChanged
        this.cargarInfoSegunTab();
    }//GEN-LAST:event_tabPanelContabilidadStateChanged

    private void btnEliminarCicloContableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCicloContableActionPerformed
        String texto = "¿Esta seguro de continuar?, Se eliminará el registro: " + this.txtTitulo.getText();
        int opc = JOptionPane.showConfirmDialog(null, texto, "¡ALERTA!", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        //System.out.println(salida);
        if (opc == 0) {
            RespuestaGeneral rg = _cicloContable.eliminar(this.cicloContableModel.getId());
            if (rg.esExitosa()) {
                JOptionPane.showMessageDialog(null, rg.getMensaje(), "INFORMACIÓN", JOptionPane.INFORMATION_MESSAGE);
                btnEliminarCicloContable.setEnabled(false);
                this.obtenerListadoCiclosContables();
            } else {
                JOptionPane.showMessageDialog(null, rg.getMensaje(), "¡ALERTA!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarCicloContableActionPerformed

    public void cargarInfoSegunTab() {
        if (this.tabPanelContabilidad.getSelectedIndex() == 0) {
            System.out.println("CICLO CONTABLE");
            this.setModelCicloContable();
            this.obtenerListadoCiclosContables();
            
        } else if (this.tabPanelContabilidad.getSelectedIndex() == 1) {
            System.out.println("CATALOGO");
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnCancelarCicloContable;
    private RSMaterialComponent.RSButtonShapeIcon btnEliminarCicloContable;
    private RSMaterialComponent.RSButtonShapeIcon btnEstablecerCicloContable;
    private RSMaterialComponent.RSButtonShapeIcon btnGuardarCicloContable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private RSMaterialComponent.RSComboBoxMaterial listCatalogo;
    private javax.swing.JTabbedPane tabPanelContabilidad;
    private rojerusan.RSTableMetro tblCicloContable;
    private newscomponents.RSDateChooser txtDesde;
    private newscomponents.RSDateChooser txtHasta;
    private RSMaterialComponent.RSTextFieldMaterial txtTitulo;
    // End of variables declaration//GEN-END:variables
}
