/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Persona;
import modelo.Usuario;
import servicios.ServicioConfiguracion;
import servicios.ServicioUsuario;
import sesion.Sesion;
import utils.UtileriaVista;
import utils.constantes.CambiaPanel;
import utils.constantes.CharArrayUtils;
import utils.constantes.Constantes;
import utils.constantes.RespuestaGeneral;

/**
 *
 * @author vacev
 */
public class vRestaurarConfiguracion extends javax.swing.JFrame {

    /**
     * Creates new form vConfigInicial
     */
    ServicioConfiguracion _configuracion;
    Sesion sesion;

    public vRestaurarConfiguracion(Sesion sesion) {
        initComponents();
        this.sesion = sesion;
        this._configuracion = new ServicioConfiguracion();
        this.iniciarVista();
        boolean esRestaurar = true;
        
//        PruebaPanelCrearUsuario panel = new PruebaPanelCrearUsuario();
        
        pCrearUsuario panel = new pCrearUsuario(
                        this.sesion, 
                        esRestaurar, 
                        Constantes.TIPO_DOCENTE, 
                        this
                );
        this.panelBase.removeAll();
        //panel.setLocation(0,0);
        //panel.setSize(500,600);
        this.panelBase.add(panel);
//        Dimension dim = panel.getPreferredSize();
//        panel.setSize(dim);
        this.pack();
        panelBase.revalidate();
        panelBase.repaint();
        this.setLocationRelativeTo(null);
    }
    
    public void iniciarVista() {
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/utils/icon/user.png")));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBase = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        panelBase.setBackground(new java.awt.Color(153, 255, 102));
        panelBase.setMaximumSize(new java.awt.Dimension(815, 537));
        panelBase.setLayout(new java.awt.BorderLayout());
        getContentPane().add(panelBase, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelBase;
    // End of variables declaration//GEN-END:variables
}
