/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package formularios;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.CicloContable;
import modelo.Cuenta;
import modelo.CicloContableFolio;
import modelo.TipoCatalogo;
import servicios.ServicioCicloContableFolio;
import servicios.ServicioCuentaBalance;
import sesion.Sesion;
import utils.UtileriaVista;
import utils.constantes.Constantes;
import utils.constantes.RespuestaGeneral;

/**
 *
 * @author vacev
 */
public class dFormCicloContableFolio extends javax.swing.JDialog {

    /**
     * Creates new form dFormFormula
     */
    
    CicloContableFolio cicloFolio = new CicloContableFolio();
    CicloContable cicloContable = new CicloContable();
    boolean realizoAccion = false;
    Sesion sesion;
    ServicioCicloContableFolio _cBalance;
    ServicioCuentaBalance _balance;
    TipoCatalogo tipoCatalogo = new TipoCatalogo();
    Cuenta cuentaAux = new Cuenta();
    RespuestaGeneral rg = new RespuestaGeneral();
    ServicioCicloContableFolio _cicloFolio;
    
    public dFormCicloContableFolio(java.awt.Frame parent, boolean modal, Sesion sesion, CicloContableFolio cBalance, CicloContable cicloContable, TipoCatalogo tipoCatalogo) {
        super(parent, modal);
        initComponents();
        this.sesion = sesion;
        this.cicloFolio = cBalance;
        this._cBalance = new ServicioCicloContableFolio(sesion.rutaConexion);
        this._balance = new ServicioCuentaBalance(sesion.rutaConexion);
        this.cicloContable = cicloContable;
        this._cicloFolio = new ServicioCicloContableFolio(this.sesion.rutaConexion);
        this.cicloContable.setId_catalogo(cicloContable.getId_catalogo());
        this.cicloFolio.setCicloContable(this.cicloContable);
        this.tipoCatalogo = tipoCatalogo;
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle(this.cicloFolio.getId() > 0 ? "MODIFICAR CUENTA O FOLIO" : "NUEVO CUENTA Y FOLIO");
        this.setearData();
        this.obtenerUltimoFolio();
    }
    
    public void obtenerUltimoFolio() {
        RespuestaGeneral rg = this._cicloFolio.ObtenerUltimoFolioPorCicloContable(this.cicloContable.getId(), this.tipoCatalogo.getId());
        if (rg.esExitosa()) {
            ArrayList<CicloContableFolio> listaAux = new ArrayList<>();
            listaAux = (ArrayList<CicloContableFolio>)rg.getDatos();
            if (listaAux.isEmpty()) {
                this.txtUltimoFolio.setText("-");
            } else {
                this.txtUltimoFolio.setText(String.valueOf(listaAux.get(0).getFolio_mayor()));
            }
        }
    }
    
    public void limpiarCuentaSeleccionada() {
        this.cicloFolio.setId_cuenta(-1);
        this.cicloFolio.setCuenta(new Cuenta());
        this.txtCuentaSeleccionada.setText("* CUENTA NO ESPECIFICADA *");
        //this.txtSaldoInicial.setText("");
    }
    
    public void setearData() {
        this.cicloFolio.setId_ciclo_contable(this.cicloContable.getId());
        if (this.cicloFolio.getId() < 0) {
            this.cicloFolio.setId_cuenta(-1);
            this.cicloFolio.setCuenta(new Cuenta());
            this.txtCuentaSeleccionada.setText("* CUENTA NO ESPECIFICADA *");
        } else {
            this.txtCuentaSeleccionada.setText(this.cicloFolio.getCuenta().getCodigo() + " - " + this.cicloFolio.getCuenta().getNombre().toUpperCase());
        }
        //this.txtSaldoInicial.setText(String.valueOf(this.cicloFolio.getSaldo_inicial() == 0 ? "" : this.cicloFolio.getSaldo_inicial()));
        //this.txtSaldoInicial.setText(String.valueOf(this.cicloFolio.getSaldo_inicial()));
        //this.txtSaldoFinal.setText(String.valueOf(this.cicloFolio.getSaldo_final()));
        this.txtFolio.setText(String.valueOf(this.cicloFolio.getFolio_mayor()));
    }

    public boolean isRealizoAccion() {
        return realizoAccion;
    }

    public void setRealizoAccion(boolean realizoAccion) {
        this.realizoAccion = realizoAccion;
    }

    public RespuestaGeneral getRg() {
        return rg;
    }

    public void setRg(RespuestaGeneral rg) {
        this.rg = rg;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCancelarTipoCatalogo = new RSMaterialComponent.RSButtonShapeIcon();
        btnGuardarTipoCatalogo = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel17 = new javax.swing.JLabel();
        btnCancelarTipoCatalogo1 = new RSMaterialComponent.RSButtonShapeIcon();
        txtCuentaSeleccionada = new javax.swing.JLabel();
        btnCancelarTipoCatalogo2 = new RSMaterialComponent.RSButtonShapeIcon();
        jLabel19 = new javax.swing.JLabel();
        txtFolio = new RSMaterialComponent.RSTextFieldMaterial();
        jLabel20 = new javax.swing.JLabel();
        txtUltimoFolio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        btnCancelarTipoCatalogo.setBackground(new java.awt.Color(251, 205, 6));
        btnCancelarTipoCatalogo.setText("CERRAR");
        btnCancelarTipoCatalogo.setToolTipText("CERRAR EL FORMULARIO");
        btnCancelarTipoCatalogo.setBackgroundHover(new java.awt.Color(251, 174, 6));
        btnCancelarTipoCatalogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelarTipoCatalogo.setForegroundHover(new java.awt.Color(0, 0, 0));
        btnCancelarTipoCatalogo.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCancelarTipoCatalogo.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnCancelarTipoCatalogo.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCancelarTipoCatalogo.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCancelarTipoCatalogo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarTipoCatalogo.setSizeIcon(18.0F);
        btnCancelarTipoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoCatalogoActionPerformed(evt);
            }
        });

        btnGuardarTipoCatalogo.setBackground(new java.awt.Color(33, 58, 86));
        btnGuardarTipoCatalogo.setText("GUARDAR");
        btnGuardarTipoCatalogo.setToolTipText("GUARDAR / ACTUALIZAR LA CUENTA");
        btnGuardarTipoCatalogo.setBackgroundHover(new java.awt.Color(33, 68, 86));
        btnGuardarTipoCatalogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardarTipoCatalogo.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnGuardarTipoCatalogo.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.SAVE);
        btnGuardarTipoCatalogo.setSizeIcon(18.0F);
        btnGuardarTipoCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarTipoCatalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarTipoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarTipoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTipoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarTipoCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Cuenta: *");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnCancelarTipoCatalogo1.setBackground(new java.awt.Color(51, 102, 255));
        btnCancelarTipoCatalogo1.setText("LIMPIAR");
        btnCancelarTipoCatalogo1.setToolTipText("QUITAR LA CUENTA SELECCIONADA");
        btnCancelarTipoCatalogo1.setBackgroundHover(new java.awt.Color(51, 153, 255));
        btnCancelarTipoCatalogo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelarTipoCatalogo1.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCancelarTipoCatalogo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarTipoCatalogo1.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarTipoCatalogo1.setSizeIcon(18.0F);
        btnCancelarTipoCatalogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoCatalogo1ActionPerformed(evt);
            }
        });

        txtCuentaSeleccionada.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCuentaSeleccionada.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtCuentaSeleccionada.setText("* CUENTA NO ESPECIFICADA *");
        txtCuentaSeleccionada.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnCancelarTipoCatalogo2.setBackground(new java.awt.Color(0, 153, 0));
        btnCancelarTipoCatalogo2.setText("ELEGIR CUENTA");
        btnCancelarTipoCatalogo2.setToolTipText("SELECCIONAR CUENTA");
        btnCancelarTipoCatalogo2.setBackgroundHover(new java.awt.Color(0, 178, 0));
        btnCancelarTipoCatalogo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCancelarTipoCatalogo2.setForma(RSMaterialComponent.RSButtonShapeIcon.FORMA.ROUND);
        btnCancelarTipoCatalogo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelarTipoCatalogo2.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.CANCEL);
        btnCancelarTipoCatalogo2.setSizeIcon(18.0F);
        btnCancelarTipoCatalogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoCatalogo2ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Folio Mayor: *");
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtFolio.setForeground(new java.awt.Color(0, 0, 0));
        txtFolio.setColorMaterial(new java.awt.Color(0, 0, 0));
        txtFolio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtFolio.setPhColor(new java.awt.Color(0, 0, 0));
        txtFolio.setPlaceholder("Digite el folio mayor");
        txtFolio.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtFolio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFolioKeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Último FM:");
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        txtUltimoFolio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUltimoFolio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtUltimoFolio.setText("FOLIO");
        txtUltimoFolio.setToolTipText("ULTIMO FOLIO INGRESADO");
        txtUltimoFolio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(btnCancelarTipoCatalogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarTipoCatalogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCuentaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUltimoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTipoCatalogo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarTipoCatalogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCuentaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFolio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUltimoFolio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarTipoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoCatalogoActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarTipoCatalogoActionPerformed

    private void btnGuardarTipoCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarTipoCatalogoActionPerformed
        // setear info al modelo
        boolean valido = this.setearModelo();
        
        if (valido) {
            // guardamos la info
            if (this.cicloFolio.getId() < 0) {
                RespuestaGeneral rg = _cBalance.insertar(this.cicloFolio);
                if (rg.esExitosa()) {
                    this.setRealizoAccion(true);
                    this.setRg(rg);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, rg.getMensaje(), "¡ALERTA!", UtileriaVista.devolverCodigoMensaje(rg));
                }

                // verificamos si es NUEVO
            } else {
                RespuestaGeneral rg = _cBalance.editar(this.cicloFolio);
                if (rg.esExitosa()) {
                    this.setRealizoAccion(true);
                    this.setRg(rg);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, rg.getMensaje(), "¡ALERTA!", UtileriaVista.devolverCodigoMensaje(rg));
                }
            }
        }
        
    }//GEN-LAST:event_btnGuardarTipoCatalogoActionPerformed

    public boolean setearModelo() {
        boolean valido = true;
        
        try {
            if (this.cicloFolio.getId_cuenta() < 0) {
                valido = false;
                JOptionPane.showMessageDialog(this, "No se ha seleccionado una cuenta", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
            }
            
            if (this.txtFolio.getText().isEmpty() || this.txtFolio.getText().trim().equals("0")) {
                valido = false;
                JOptionPane.showMessageDialog(this, "No se ha digitado el folio mayor", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
            } else {
                this.cicloFolio.setFolio_mayor(Integer.parseInt(this.txtFolio.getText()));
            }
            
        } catch (Exception e) {
            valido = false;
            JOptionPane.showMessageDialog(this, "Por favor verifique que todos los campos han sido completados", "¡Alerta!", JOptionPane.WARNING_MESSAGE);
        }
        
        return valido;
        //this.cicloFolio.getFormula().setPosicion();
    }
    
    private void btnCancelarTipoCatalogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoCatalogo1ActionPerformed
        this.limpiarCuentaSeleccionada();
    }//GEN-LAST:event_btnCancelarTipoCatalogo1ActionPerformed

    private void btnCancelarTipoCatalogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoCatalogo2ActionPerformed
        dSeleccionarCuentaFormula d = new dSeleccionarCuentaFormula(null, true, sesion, this.tipoCatalogo, true, this.tipoCatalogo.getNivel_mayorizar(), this.cicloContable);
        d.setVisible(true);
        // validamos si realizo alguna accion para actualizar el listado o no
        if (d.getRealizoAccion()) {
            //JOptionPane.showMessageDialog(this, d.getRg().getMensaje(), "INFORMACIÓN", UtileriaVista.devolverCodigoMensaje(d.getRg()));
            this.cicloFolio.setId_cuenta(d.getCuentaSeleccionada().getId());
            this.txtCuentaSeleccionada.setText(d.getCuentaSeleccionada().getCodigo() + " - " + d.getCuentaSeleccionada().getNombre());
            this.cuentaAux = d.getCuentaSeleccionada();
            this.txtFolio.setText(String.valueOf(this.cuentaAux.getFolio_mayor()));
        }
    }//GEN-LAST:event_btnCancelarTipoCatalogo2ActionPerformed

    private void txtFolioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFolioKeyTyped
        if (!Constantes.validarNumeros(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtFolioKeyTyped

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(dFormFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(dFormFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(dFormFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(dFormFormula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                dFormFormula dialog = new dFormFormula(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private RSMaterialComponent.RSButtonShapeIcon btnCancelarTipoCatalogo;
    private RSMaterialComponent.RSButtonShapeIcon btnCancelarTipoCatalogo1;
    private RSMaterialComponent.RSButtonShapeIcon btnCancelarTipoCatalogo2;
    private RSMaterialComponent.RSButtonShapeIcon btnGuardarTipoCatalogo;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtCuentaSeleccionada;
    private RSMaterialComponent.RSTextFieldMaterial txtFolio;
    private javax.swing.JLabel txtUltimoFolio;
    // End of variables declaration//GEN-END:variables
}
